# Generated by Django 6.0.3 on 2026-03-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('I', 'Phase I'), ('II', 'Phase II'), ('III', 'Phase III'), ('IV', 'Phase IV')], max_length=10)),
                ('beginning_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active_agent', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100)),
                ('inclusion_date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='clinical_app.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='clinical_app.patient')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='clinical_app.clinicaltrial')),
            ],
        ),
        migrations.CreateModel(
            name='UndesirableEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_occurrence', models.DateField()),
                ('grade', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undesirable_effects', to='clinical_app.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undesirable_effects', to='clinical_app.patient')),
                ('side_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undesirable_effects', to='clinical_app.sideeffect')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undesirable_effects', to='clinical_app.clinicaltrial')),
            ],
        ),
    ]
